-- Insertar indicadores electorales de conocimiento
USE estadisticas_db;

INSERT INTO tbl_formulas (indicador, sigla, tipo_indicador, formula, explicacion, observaciones, enunciado_antes, enunciado_ahora, notas_adicionales, habilitado, tbl_usuario_id, dtcreate) VALUES

-- 1. Porcentaje de personas que conocen al candidato
('Personas que dicen conocerla', '% CONOCEN', 'Electoral Conocimiento', 'FILTRO DE PERSONAS ENCUESTA QUE DICEN OPCION SI A CONOCER EL CANDIDATO', 'CONTEO PERSONAS ENCUESTA QUE DICEN CONOCER AL CANDIDATO', 'La fórmula y los cálculos son consistentes, no obstante, se sugiere construir intervalos de confianza al 95%.', 'La conocen el 70% de las personas', 'La conocen entre el 68% y el 71% de las personas', NULL, 'si', 1, NOW()),

-- 2. Proyección de votantes que lo conocen
('Proyección de votantes que lo conocen', 'NCC', 'Electoral Conocimiento', 'VOTOS 2A VUELTA * % PERSONAS ENCUESTA QUE DIJERON CONOCER AL CANDIDATO', 'APLICACIÓN DEL PORCENTAJE DE CONOCIMIENTO A LA ULTIMA VOTACION', 'La fórmula es consistente pero los cálculos no, puesto que se tomó como total de votos de segunda vuelta los resultados del preconteo (22658694) y no los resultados de escrutinio oficiales que son ligeramente superiores (22687910). Además, no perder de vista que es una proyección sobre segunda vuelta donde históricamente suelen votar más personas.', 'Proyección de votantes que la conocen: 15.763.547', 'Proyección de votantes que la conocen: 15.783.872', NULL, 'si', 1, NOW()),

-- 3. Crecimiento del conocimiento mensual
('Crecimiento del conocimiento mensual', 'NRP', 'Electoral Conocimiento', '[(#PERSONAS QUE LA CONOCE/MUESTRA )+(#PERSONAS QUE TIENEN IMAGEN FAVORABLE CANDIDATO / MUESTRA )]/ TIEMPO PARA LA ELECCION', 'NIVEL DE RECONOCIMIENTO EN UN PERIODO DE TIEMPO', 'No es una fórmula estándar (esto puede ser su valor agregado), aunque hay que tener cuidado con su interpretación. No es un ritmo de crecimiento sino un posicionamiento o tracción. Si se monitorea cada 1, 2 o 3 meses el resultado debería crecer, y lo que más jalona o genera tracción es que más personas conozcan a la candidata.', 'N/A', 'N/A', NULL, 'si', 1, NOW()),

-- 4. Tasa de conversión a votos
('Tasa de conversión a votos', 'TC', 'Electoral Conocimiento', '[(#PERSONAS QUE DICEN CONOCERLA - #PERSONAS CON IMAGEN FAVORABLE DEL CANDIDATO)+ (#PERSONAS CON IMAGEN FAVORABLE DEL CANDIDATO  - #PERSONAS QUE DICEN QUE SI VOTARIAN POR ESE CANDIDATO)]/#PERSONAS QUE DICEN CONOCER AL CANDIDATO', 'ES LA DIFERENCIA POSITIVA DE MERMAS ENTRE LOS QUE DICEN CONOCERLO Y LOS QUE DICEN VOTAR POR EL CON LA RESTRICCION DE LOS QUE DICEN TENER IMAGEN FAVORABLE ESTE VALOR ES QUE REPLICA EN PERIODO Y EN EL ESPACIO DE CRECIMIENTO PARA MEJORAR LOS INDICADORES DE ELECTORALES', 'En la fórmula actual se están cancelando el número de personas con imagen favorable del candidato (primero las resto y luego las sumo). Al hacer esto en el numerador queda: (La conocen - Votarían por ella) = Personas que la conocen pero NO votarían por ella. Entonces no está calculando la conversión que tengo sino la conversión que me falta. Dicho lo anterior, yo la simplificaría a una o dos tasas de conversión primarias: de los que la conocen o tienen imagen favorable cuántos votarían por ella, y haría el monitoreo de esa proporción buscando que crezca, y si eso sucede, vamos por buen camino.', 'Tasa de conversión: 63%', 'Tasa de conversión con base en conocimiento = (Votarían por ella / La conocen) = 37%. Nota: también se podría calcular otra tasa de conversión con base en favorabilidad: (Votarían por ella / Tienen imagen favorable) = 76%', 'Nota adicional, caso Claudia: la tasa de conversión con base en favorabilidad es más del doble que la tasa de conversión con base en el conocimiento, lo que en mi concepto plantea dos retos: 1. Incrementar su favoribilidad en términos generales. 2. Incrementar su favorabilidad entre quienes ya la conocen, es decir, se pueden pensar estrategias para llegar a personas que no la conozcan, sin embargo, hay un espacio de crecimiento considerable entre quienes ya la conocen.', 'si', 1, NOW()),

-- 5. Nivel de posicionamiento del candidato
('Nivel de posicionamiento del candidato', 'NPP', 'Electoral Conocimiento', '(#PERSONAS QUE DICEN CONOCERLO  - #PERSONAS QUE TIENE IMAGEN FAVORABLE)/ MUESTRA', 'ES LA CIFRA QUE EL CANDIDATO OCUPA CON LA MUESTRA Y COBERTURA HECHA CON LA MERMA ENTRE EL RECONOCIMIENTO Y LA IMAGEN FAVORABLE', 'No es una fórmula consistente. Asumamos que 100 personas la conocen y las 100 tienen imagen favorable (escenario ideal), en ese caso, el numerador sería 0 y el cálculo de posicionamiento daría 0 independientemente del tamaño de muestra. Desde mi lectura, tal vez un poco más ortodoxa, el mejor indicador de posicionamiento es la intención de voto, sobre ese valor es que salen titulares, es la cifra que más cala y es lo más fácil de entender para todo el mundo.', 'N/A', 'N/A', NULL, 'si', 1, NOW()),

-- 6. Vectorial del crecimiento del conocimiento
('Vectorial del crecimiento del conocimiento', 'VCC', 'Electoral Conocimiento', '(TC/  VOTOS DE LA COBERTURA DEL ESTUDIO )', 'PARA HACER EL COMPARATIVO CON OTRAS ENCUESTAS CON LA COBERTURA DE ELLA Y CON ESO VERIFICAR LA INTENCION DE VOTO DE LA PROPIA Y LA AJENA', 'La fórmula y los cálculos son consistentes, no obstante, revisar los comentarios sobre el cálculo de la tasa de conversión.', 'N/A', 'N/A', NULL, 'si', 1, NOW()),

-- 7. Tasa electoral por conocimiento
('Tasa electoral por conocimiento', 'TEC', 'Electoral Conocimiento', '( # PERSONAS QUE VOTAN ***SI VOTARIAN POR EL CANDIDATO***/ # PERSONAS QUE DICEN CONOCER AL CANDIDATO)', 'ES LA CIFRA QUE EL CANDIDATO OCUPA EN EL ESTUDIO CON LA COBERTURA EN MOMENTO. ES LA CAPACIDAD DE CONVERTIR SU CONOCIMIENTO EN VOTOS', 'No se entiende la fórmula. ¿Qué significan los 3 asteriscos en el numerador?', 'N/A', 'N/A', NULL, 'si', 1, NOW());

-- Verificar inserción
SELECT COUNT(*) AS total_formulas FROM tbl_formulas;
SELECT id, sigla, indicador, tipo_indicador FROM tbl_formulas ORDER BY id;
