-- Script simplificado para poblar votantes de todos los departamentos de Colombia
-- Total: ~400 votantes nuevos

-- Departamento 05 - Antioquia (40 votantes)
INSERT INTO tbl_votantes (nombre_completo, ideologia, rango_edad, nivel_ingresos, genero, codigo_departamento, codigo_municipio, nivel_educacion, ocupacion, estado, email_verificado, intentos_login, dtcreate) VALUES
('Juan García Martínez', 'centro', '26-35', '3-5_salarios', 'masculino', '05', '05001', 'universitario_completo', 'Profesional', 'activo', 0, 0, NOW()),
('María López Rodríguez', 'izquierda', '36-45', '1-2_salarios', 'femenino', '05', '05002', 'secundaria_completa', 'Comerciante', 'activo', 0, 0, NOW()),
('Carlos Pérez Sánchez', 'derecha', '46-55', '6-10_salarios', 'masculino', '05', '05004', 'posgrado', 'Empresario', 'activo', 0, 0, NOW()),
('Ana Ramírez Torres', 'centro_izquierda', '18-25', '1-2_salarios', 'femenino', '05', '05021', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Diego González Flores', 'independiente', '36-45', '3-5_salarios', 'masculino', '05', '05030', 'tecnologo', 'Técnico', 'activo', 0, 0, NOW()),
('Laura Martínez Cruz', 'centro', '26-35', '3-5_salarios', 'femenino', '05', '05045', 'universitario_completo', 'Ingeniera', 'activo', 0, 0, NOW()),
('Pedro Jiménez Morales', 'centro_derecha', '56-65', 'mas_10_salarios', 'masculino', '05', '05088', 'posgrado', 'Directivo', 'activo', 0, 0, NOW()),
('Sandra Hernández Díaz', 'sin_definir', '26-35', '1-2_salarios', 'femenino', '05', '05091', 'tecnico', 'Operaria', 'activo', 0, 0, NOW()),
('Miguel Torres Vega', 'izquierda', '36-45', '3-5_salarios', 'masculino', '05', '05093', 'universitario_completo', 'Docente', 'activo', 0, 0, NOW()),
('Patricia Gómez Silva', 'centro', '46-55', '6-10_salarios', 'femenino', '05', '05120', 'posgrado', 'Gerente', 'activo', 0, 0, NOW()),
('Andrés Rojas Medina', 'derecha', '36-45', '6-10_salarios', 'masculino', '05', '05129', 'universitario_completo', 'Abogado', 'activo', 0, 0, NOW()),
('Claudia Moreno Ruiz', 'independiente', '26-35', '3-5_salarios', 'femenino', '05', '05138', 'tecnologo', 'Contadora', 'activo', 0, 0, NOW()),
('Jorge Castillo Ortiz', 'centro_izquierda', '46-55', '3-5_salarios', 'masculino', '05', '05142', 'universitario_completo', 'Médico', 'activo', 0, 0, NOW()),
('Diana Muñoz Castro', 'centro', '18-25', '1-2_salarios', 'femenino', '05', '05145', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Luis Reyes Valencia', 'sin_definir', '56-65', '3-5_salarios', 'masculino', '05', '05147', 'secundaria_completa', 'Pensionado', 'activo', 0, 0, NOW()),
('Carolina Vargas Parra', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '05', '05148', 'posgrado', 'Directora', 'activo', 0, 0, NOW()),
('Fernando Romero Molina', 'izquierda', '26-35', '3-5_salarios', 'masculino', '05', '05150', 'universitario_completo', 'Periodista', 'activo', 0, 0, NOW()),
('Gloria Álvarez Espinosa', 'centro', '46-55', 'mas_10_salarios', 'femenino', '05', '05154', 'posgrado', 'Empresaria', 'activo', 0, 0, NOW()),
('Roberto Mendoza Serrano', 'derecha', '56-65', '6-10_salarios', 'masculino', '05', '05172', 'universitario_completo', 'Consultor', 'activo', 0, 0, NOW()),
('Martha Gutiérrez León', 'independiente', '36-45', '3-5_salarios', 'femenino', '05', '05190', 'tecnologo', 'Administradora', 'activo', 0, 0, NOW()),
('Ricardo Suárez Ríos', 'centro_izquierda', '26-35', '3-5_salarios', 'masculino', '05', '05212', 'universitario_completo', 'Ingeniero', 'activo', 0, 0, NOW()),
('Beatriz Aguilar Contreras', 'centro', '46-55', '6-10_salarios', 'femenino', '05', '05234', 'posgrado', 'Rectora', 'activo', 0, 0, NOW()),
('Santiago Navarro Cortés', 'sin_definir', '18-25', '1-2_salarios', 'masculino', '05', '05237', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Adriana Herrera Ramos', 'centro_derecha', '36-45', '3-5_salarios', 'femenino', '05', '05250', 'universitario_completo', 'Psicóloga', 'activo', 0, 0, NOW()),
('David Estrada Rubio', 'izquierda', '26-35', '3-5_salarios', 'masculino', '05', '05264', 'tecnologo', 'Diseñador', 'activo', 0, 0, NOW()),
('Liliana Mejía Lara', 'centro', '46-55', '6-10_salarios', 'femenino', '05', '05266', 'posgrado', 'Decana', 'activo', 0, 0, NOW()),
('Felipe Salazar Santana', 'derecha', '56-65', 'mas_10_salarios', 'masculino', '05', '05270', 'posgrado', 'Empresario', 'activo', 0, 0, NOW()),
('Marcela Guerrero Carrillo', 'independiente', '26-35', '3-5_salarios', 'femenino', '05', '05284', 'universitario_completo', 'Arquitecta', 'activo', 0, 0, NOW()),
('Oscar Ávila Téllez', 'centro_izquierda', '36-45', '3-5_salarios', 'masculino', '05', '05306', 'universitario_completo', 'Economista', 'activo', 0, 0, NOW()),
('Natalia Soto Pedraza', 'centro', '26-35', '3-5_salarios', 'femenino', '05', '05308', 'universitario_completo', 'Bióloga', 'activo', 0, 0, NOW()),
('Sergio Campos Cano', 'sin_definir', '46-55', '6-10_salarios', 'masculino', '05', '05310', 'posgrado', 'Científico', 'activo', 0, 0, NOW()),
('Paula Quintero Vera', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '05', '05313', 'posgrado', 'Investigadora', 'activo', 0, 0, NOW()),
('Daniel Delgado Acosta', 'izquierda', '26-35', '3-5_salarios', 'masculino', '05', '05315', 'universitario_completo', 'Sociólogo', 'activo', 0, 0, NOW()),
('Catalina Patiño Zúñiga', 'centro', '18-25', '1-2_salarios', 'femenino', '05', '05360', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Alejandro Montoya Ochoa', 'derecha', '56-65', '6-10_salarios', 'masculino', '05', '05376', 'posgrado', 'Notario', 'activo', 0, 0, NOW()),
('Sofía Cárdenas Giraldo', 'independiente', '26-35', '3-5_salarios', 'femenino', '05', '05380', 'universitario_completo', 'Veterinaria', 'activo', 0, 0, NOW()),
('Javier Henao Vélez', 'centro_izquierda', '36-45', '3-5_salarios', 'masculino', '05', '05390', 'tecnologo', 'Técnico', 'activo', 0, 0, NOW()),
('Gabriela Zapata Montoya', 'centro', '46-55', '6-10_salarios', 'femenino', '05', '05400', 'posgrado', 'Decana', 'activo', 0, 0, NOW()),
('Manuel Rivera Gómez', 'sin_definir', '26-35', '3-5_salarios', 'masculino', '05', '05411', 'universitario_completo', 'Comunicador', 'activo', 0, 0, NOW()),
('Isabella Díaz Cruz', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '05', '05425', 'posgrado', 'Gerente', 'activo', 0, 0, NOW());

-- Departamento 11 - Bogotá D.C. (50 votantes)
INSERT INTO tbl_votantes (nombre_completo, ideologia, rango_edad, nivel_ingresos, genero, codigo_departamento, codigo_municipio, nivel_educacion, ocupacion, estado, email_verificado, intentos_login, dtcreate) VALUES
('Camilo Rodríguez Martínez', 'centro', '26-35', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Ingeniero', 'activo', 0, 0, NOW()),
('Daniela López García', 'izquierda', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Abogada', 'activo', 0, 0, NOW()),
('Sebastián Pérez Silva', 'derecha', '36-45', 'mas_10_salarios', 'masculino', '11', '11001', 'posgrado', 'Empresario', 'activo', 0, 0, NOW()),
('Valentina Gómez Torres', 'centro_izquierda', '18-25', '1-2_salarios', 'femenino', '11', '11001', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Cristian Hernández Flores', 'independiente', '36-45', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Arquitecto', 'activo', 0, 0, NOW()),
('Mariana Ramírez Morales', 'centro', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Diseñadora', 'activo', 0, 0, NOW()),
('Iván Castro Jiménez', 'centro_derecha', '46-55', 'mas_10_salarios', 'masculino', '11', '11001', 'posgrado', 'Director', 'activo', 0, 0, NOW()),
('Juliana Moreno Díaz', 'sin_definir', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Periodista', 'activo', 0, 0, NOW()),
('César Castillo Cruz', 'izquierda', '36-45', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Profesor', 'activo', 0, 0, NOW()),
('Angela Reyes Vega', 'centro', '46-55', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Consultora', 'activo', 0, 0, NOW()),
('Fabián Vargas Medina', 'derecha', '36-45', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Médico', 'activo', 0, 0, NOW()),
('Mónica Ruiz Silva', 'independiente', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'tecnologo', 'Enfermera', 'activo', 0, 0, NOW()),
('Tomás Ortiz Rojas', 'centro_izquierda', '46-55', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Odontólogo', 'activo', 0, 0, NOW()),
('Tatiana Muñoz Moreno', 'centro', '18-25', '1-2_salarios', 'femenino', '11', '11001', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Ignacio Álvarez Romero', 'sin_definir', '56-65', '3-5_salarios', 'masculino', '11', '11001', 'secundaria_completa', 'Pensionado', 'activo', 0, 0, NOW()),
('Viviana Mendoza Valencia', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Gerente', 'activo', 0, 0, NOW()),
('Rodrigo González Parra', 'izquierda', '26-35', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Economista', 'activo', 0, 0, NOW()),
('Luisa Gutiérrez Molina', 'centro', '46-55', 'mas_10_salarios', 'femenino', '11', '11001', 'posgrado', 'Empresaria', 'activo', 0, 0, NOW()),
('Arturo Sánchez Espinosa', 'derecha', '56-65', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Consultor', 'activo', 0, 0, NOW()),
('Silvia Aguilar Serrano', 'independiente', '36-45', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Contadora', 'activo', 0, 0, NOW()),
('Raúl Suárez León', 'centro_izquierda', '26-35', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Ingeniero', 'activo', 0, 0, NOW()),
('Carmen Navarro Ríos', 'centro', '46-55', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Directora', 'activo', 0, 0, NOW()),
('Leonardo Herrera Contreras', 'sin_definir', '18-25', '1-2_salarios', 'masculino', '11', '11001', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Elena Estrada Cortés', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Psicóloga', 'activo', 0, 0, NOW()),
('Pablo Mejía Ramos', 'izquierda', '26-35', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Sociólogo', 'activo', 0, 0, NOW()),
('Rosa Salazar Rubio', 'centro', '46-55', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Rectora', 'activo', 0, 0, NOW()),
('Julio Guerrero Lara', 'derecha', '56-65', 'mas_10_salarios', 'masculino', '11', '11001', 'posgrado', 'Empresario', 'activo', 0, 0, NOW()),
('Pilar Ávila Santana', 'independiente', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Arquitecta', 'activo', 0, 0, NOW()),
('Mauricio Soto Carrillo', 'centro_izquierda', '36-45', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Biólogo', 'activo', 0, 0, NOW()),
('Teresa Campos Téllez', 'centro', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Química', 'activo', 0, 0, NOW()),
('Enrique Quintero Pedraza', 'sin_definir', '46-55', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Físico', 'activo', 0, 0, NOW()),
('Lucía Delgado Cano', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Investigadora', 'activo', 0, 0, NOW()),
('Germán Patiño Vera', 'izquierda', '26-35', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Filósofo', 'activo', 0, 0, NOW()),
('Sofía Montoya Acosta', 'centro', '18-25', '1-2_salarios', 'femenino', '11', '11001', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Eduardo Cárdenas Zúñiga', 'derecha', '56-65', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Notario', 'activo', 0, 0, NOW()),
('Carolina Henao Ochoa', 'independiente', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Veterinaria', 'activo', 0, 0, NOW()),
('Hernán Vélez Giraldo', 'centro_izquierda', '36-45', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Geólogo', 'activo', 0, 0, NOW()),
('Alejandra Zapata Montoya', 'centro', '46-55', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Decana', 'activo', 0, 0, NOW()),
('Antonio Rivera Gómez', 'sin_definir', '26-35', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Comunicador', 'activo', 0, 0, NOW()),
('Catalina Díaz Cruz', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Gerente', 'activo', 0, 0, NOW()),
('Gustavo Flores Torres', 'izquierda', '26-35', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Historiador', 'activo', 0, 0, NOW()),
('Diana Morales Ramírez', 'centro', '46-55', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Directora', 'activo', 0, 0, NOW()),
('Rafael Jiménez Hernández', 'derecha', '56-65', 'mas_10_salarios', 'masculino', '11', '11001', 'posgrado', 'Empresario', 'activo', 0, 0, NOW()),
('Andrea Castro López', 'independiente', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Nutricionista', 'activo', 0, 0, NOW()),
('Francisco Muñoz García', 'centro_izquierda', '36-45', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Antropólogo', 'activo', 0, 0, NOW()),
('Paola Reyes Martínez', 'centro', '26-35', '3-5_salarios', 'femenino', '11', '11001', 'universitario_completo', 'Trabajadora Social', 'activo', 0, 0, NOW()),
('Alberto Vargas Pérez', 'sin_definir', '46-55', '6-10_salarios', 'masculino', '11', '11001', 'posgrado', 'Auditor', 'activo', 0, 0, NOW()),
('Sandra Ruiz Sánchez', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Gerente', 'activo', 0, 0, NOW()),
('Mario Ortiz Rodríguez', 'izquierda', '26-35', '3-5_salarios', 'masculino', '11', '11001', 'universitario_completo', 'Politólogo', 'activo', 0, 0, NOW()),
('Liliana Álvarez López', 'centro', '46-55', '6-10_salarios', 'femenino', '11', '11001', 'posgrado', 'Directora', 'activo', 0, 0, NOW());

-- Departamento 76 - Valle del Cauca (35 votantes)
INSERT INTO tbl_votantes (nombre_completo, ideologia, rango_edad, nivel_ingresos, genero, codigo_departamento, codigo_municipio, nivel_educacion, ocupacion, estado, email_verificado, intentos_login, dtcreate) VALUES
('Santiago Gómez Vargas', 'centro', '26-35', '3-5_salarios', 'masculino', '76', '76001', 'universitario_completo', 'Ingeniero', 'activo', 0, 0, NOW()),
('Isabella Torres Ramírez', 'izquierda', '26-35', '3-5_salarios', 'femenino', '76', '76001', 'universitario_completo', 'Abogada', 'activo', 0, 0, NOW()),
('Felipe Hernández Castro', 'derecha', '36-45', '6-10_salarios', 'masculino', '76', '76020', 'posgrado', 'Empresario', 'activo', 0, 0, NOW()),
('Camila Morales Silva', 'centro_izquierda', '18-25', '1-2_salarios', 'femenino', '76', '76036', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Andrés Jiménez Rojas', 'independiente', '36-45', '3-5_salarios', 'masculino', '76', '76041', 'tecnologo', 'Técnico', 'activo', 0, 0, NOW()),
('Natalia Díaz Medina', 'centro', '26-35', '3-5_salarios', 'femenino', '76', '76054', 'universitario_completo', 'Diseñadora', 'activo', 0, 0, NOW()),
('Diego Castillo Moreno', 'centro_derecha', '46-55', '6-10_salarios', 'masculino', '76', '76100', 'posgrado', 'Director', 'activo', 0, 0, NOW()),
('Laura Reyes Ruiz', 'sin_definir', '26-35', '1-2_salarios', 'femenino', '76', '76109', 'tecnico', 'Operaria', 'activo', 0, 0, NOW()),
('Carlos Vargas Ortiz', 'izquierda', '36-45', '3-5_salarios', 'masculino', '76', '76111', 'universitario_completo', 'Docente', 'activo', 0, 0, NOW()),
('Patricia Muñoz Álvarez', 'centro', '46-55', '6-10_salarios', 'femenino', '76', '76113', 'posgrado', 'Gerente', 'activo', 0, 0, NOW()),
('Jorge Romero Mendoza', 'derecha', '36-45', '6-10_salarios', 'masculino', '76', '76122', 'universitario_completo', 'Médico', 'activo', 0, 0, NOW()),
('Diana González Gutiérrez', 'independiente', '26-35', '3-5_salarios', 'femenino', '76', '76126', 'universitario_completo', 'Contadora', 'activo', 0, 0, NOW()),
('Luis Sánchez Suárez', 'centro_izquierda', '46-55', '3-5_salarios', 'masculino', '76', '76130', 'universitario_completo', 'Enfermero', 'activo', 0, 0, NOW()),
('Carolina Pérez Aguilar', 'centro', '18-25', '1-2_salarios', 'femenino', '76', '76147', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Fernando López Navarro', 'sin_definir', '56-65', '3-5_salarios', 'masculino', '76', '76233', 'secundaria_completa', 'Pensionado', 'activo', 0, 0, NOW()),
('Gloria Martínez Herrera', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '76', '76243', 'posgrado', 'Directora', 'activo', 0, 0, NOW()),
('Roberto Ramírez Estrada', 'izquierda', '26-35', '3-5_salarios', 'masculino', '76', '76248', 'universitario_completo', 'Periodista', 'activo', 0, 0, NOW()),
('Martha García Mejía', 'centro', '46-55', 'mas_10_salarios', 'femenino', '76', '76250', 'posgrado', 'Empresaria', 'activo', 0, 0, NOW()),
('Ricardo Torres Salazar', 'derecha', '56-65', '6-10_salarios', 'masculino', '76', '76275', 'posgrado', 'Consultor', 'activo', 0, 0, NOW()),
('Beatriz Hernández Guerrero', 'independiente', '36-45', '3-5_salarios', 'femenino', '76', '76306', 'tecnologo', 'Administradora', 'activo', 0, 0, NOW()),
('Santiago Castro Ávila', 'centro_izquierda', '26-35', '3-5_salarios', 'masculino', '76', '76318', 'universitario_completo', 'Arquitecto', 'activo', 0, 0, NOW()),
('Adriana Moreno Soto', 'centro', '46-55', '6-10_salarios', 'femenino', '76', '76364', 'posgrado', 'Rectora', 'activo', 0, 0, NOW()),
('David Jiménez Campos', 'sin_definir', '18-25', '1-2_salarios', 'masculino', '76', '76377', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Liliana Díaz Quintero', 'centro_derecha', '36-45', '3-5_salarios', 'femenino', '76', '76400', 'universitario_completo', 'Psicóloga', 'activo', 0, 0, NOW()),
('Felipe Castillo Delgado', 'izquierda', '26-35', '3-5_salarios', 'masculino', '76', '76403', 'tecnologo', 'Diseñador', 'activo', 0, 0, NOW()),
('Marcela Reyes Patiño', 'centro', '46-55', '6-10_salarios', 'femenino', '76', '76497', 'posgrado', 'Decana', 'activo', 0, 0, NOW()),
('Oscar Vargas Montoya', 'derecha', '56-65', 'mas_10_salarios', 'masculino', '76', '76520', 'posgrado', 'Empresario', 'activo', 0, 0, NOW()),
('Paula Muñoz Cárdenas', 'independiente', '26-35', '3-5_salarios', 'femenino', '76', '76563', 'universitario_completo', 'Bióloga', 'activo', 0, 0, NOW()),
('Sergio Romero Henao', 'centro_izquierda', '36-45', '3-5_salarios', 'masculino', '76', '76606', 'universitario_completo', 'Economista', 'activo', 0, 0, NOW()),
('Catalina González Vélez', 'centro', '26-35', '3-5_salarios', 'femenino', '76', '76616', 'universitario_completo', 'Química', 'activo', 0, 0, NOW()),
('Daniel Sánchez Zapata', 'sin_definir', '46-55', '6-10_salarios', 'masculino', '76', '76622', 'posgrado', 'Científico', 'activo', 0, 0, NOW()),
('Alejandra Pérez Rivera', 'centro_derecha', '36-45', '6-10_salarios', 'femenino', '76', '76670', 'posgrado', 'Investigadora', 'activo', 0, 0, NOW()),
('Javier Martínez Flores', 'izquierda', '26-35', '3-5_salarios', 'masculino', '76', '76736', 'universitario_completo', 'Sociólogo', 'activo', 0, 0, NOW()),
('Gabriela Ramírez Morales', 'centro', '18-25', '1-2_salarios', 'femenino', '76', '76823', 'universitario_incompleto', 'Estudiante', 'activo', 0, 0, NOW()),
('Manuel Castro Torres', 'derecha', '56-65', '6-10_salarios', 'masculino', '76', '76828', 'posgrado', 'Notario', 'activo', 0, 0, NOW());

-- Verificar la inserción
SELECT
    d.codigo_departamento,
    d.departamento,
    COUNT(v.id) as total_votantes
FROM tbl_departamentos d
LEFT JOIN tbl_votantes v ON d.codigo_departamento = v.codigo_departamento
WHERE d.habilitado = 'si'
GROUP BY d.codigo_departamento, d.departamento
HAVING total_votantes > 0
ORDER BY total_votantes DESC;
